version: '3.8'

services:
  relay:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - RELAY_SERVER_PORT=8081
      - RELAY_SERVER_HOST=0.0.0.0
      - RELAY_STAG_URL=http://host.docker.internal:8080
      - RELAY_WEBSOCKET_BUFFER_SIZE=1024
      - RELAY_WEBSOCKET_HEARTBEAT_INTERVAL=30s
      - RELAY_BATCH_MAX_SIZE=5
      - RELAY_BATCH_TIMEOUT=100ms
    networks:
      - tabular
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - tabular
    restart: unless-stopped

networks:
  tabular:
    driver: bridge